version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cogConverterApp
    ports:
      - "8080:8080"
    depends_on:
      - gdalApi
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - GDAL_API_URL=http://gdalApi:5000

  gdalApi:
    build:
      context: .
      dockerfile: Dockerfile.gdalApi
    container_name: cogConverterGdalApi
    ports:
      - "5000:5000"