services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cog-converter-app
    ports:
      - "8080:8080"
    depends_on:
      - gdalapi
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - APP_GDAL_API_URL=http://gdalapi:5000
    volumes:
      - ./tempData:/tmp/cogConverter

  gdalapi:
    build:
      context: .
      dockerfile: Dockerfile.gdalApi
    container_name: cog-converter-gdalapi
    ports:
      - "5000:5000"
    volumes:
      - ./tempData:/tmp/cogConverter
