FROM python:3.9-slim

RUN apt-get update && apt-get install -y \
    gdal-bin \
    libgdal-dev \
    g++ \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
    flask \
    rio-cogeo \
    rasterio \
    numpy \
    gunicorn

WORKDIR /app

COPY gdalApiServer.py .

EXPOSE 5000

CMD ["gunicorn", "-b", "0.0.0.0:5000", "gdalApiServer:app"]