# application.yml
server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true
        use_sql_comments: true
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

aws:
  credentials:
    path: classpath:tester-Gimjunhyeong-pickjog-1744961165_credentials.json

app:
  cog:
    temp-dir: /tmp/cogConverter
    timeout-millis: 900000
  gdal-api:
    url: http://gdalApi:5000

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    com.geotiff: DEBUG
    org.springframework.web.client: DEBUG

decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: true
      logging: slf4j